package com.briup.apps.ej.dao;

import com.briup.apps.ej.bean.OderLine;
import com.briup.apps.ej.bean.OderLineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OderLineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order_line
     *
     * @mbg.generated Mon Jun 10 15:23:51 GMT+08:00 2019
     */
    long countByExample(OderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order_line
     *
     * @mbg.generated Mon Jun 10 15:23:51 GMT+08:00 2019
     */
    int deleteByExample(OderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order_line
     *
     * @mbg.generated Mon Jun 10 15:23:51 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order_line
     *
     * @mbg.generated Mon Jun 10 15:23:51 GMT+08:00 2019
     */
    int insert(OderLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order_line
     *
     * @mbg.generated Mon Jun 10 15:23:51 GMT+08:00 2019
     */
    int insertSelective(OderLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order_line
     *
     * @mbg.generated Mon Jun 10 15:23:51 GMT+08:00 2019
     */
    List<OderLine> selectByExample(OderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order_line
     *
     * @mbg.generated Mon Jun 10 15:23:51 GMT+08:00 2019
     */
    OderLine selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order_line
     *
     * @mbg.generated Mon Jun 10 15:23:51 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") OderLine record, @Param("example") OderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order_line
     *
     * @mbg.generated Mon Jun 10 15:23:51 GMT+08:00 2019
     */
    int updateByExample(@Param("record") OderLine record, @Param("example") OderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order_line
     *
     * @mbg.generated Mon Jun 10 15:23:51 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(OderLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order_line
     *
     * @mbg.generated Mon Jun 10 15:23:51 GMT+08:00 2019
     */
    int updateByPrimaryKey(OderLine record);
}